// import './scripts/decontraction_api.js'
// import './scripts/word_count.js'

import './styles/index.css'
import './styles/fonts.css'
import './styles/interface/text-area.css'
import './styles/interface/button-panel/btn-start-count-word.css'
import './styles/interface/input-file.css'
import './styles/interface/button-panel/icons.css'
import './styles/interface/button-panel/button-panel.css'
import './styles/interface/container-user-text-menu.css'
import './scripts/card_scripts/handlers.js'
import './scripts/card_scripts/data.js'
import './scripts/user_input_handling.js'
import './scripts/dom/dom_functions.js'